name: Update Blog Entries

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  update-blog-entries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate new content for index.html
      run: |
        new_content=""
        while IFS= read -r file; do
          date_line=$(sed -n '18 { s/^[ \t]*//; s/[ \t]*$//; s/\r//g; s/^"//; s/"$//; p; }' "$file" | tr -d '\n')
          content_line=$(sed -n '22 { s/^[ \t]*//; s/[ \t]*$//; s/\r//g; s/^"//; s/"$//; p; }' "$file" | tr -d '\n')
          file_url=$(echo "$file" | sed 's|^./||')
          filename=$(basename "$file" .html)
      
          # Create HTML entry for the blog
          new_content="${new_content}<br>\n<div class=\"blog\">\n<h2>${filename}</h2>\n<p>${content_line}</p>\n<a href=\"${file_url}\">Details</a>\n</div>\n<br>\n"
        done < <(find . -type f -name "*.html" \
                    -not -name "index.html" \
                    -not -name "template.html" \
                    -not -path '*/\.*')

        # Debug: Output the new content
        echo "Generated Content:"
        echo -e "$new_content"  # Output to console for verification

        # Redirect to generated_content.html
        echo -e "$new_content" > $GITHUB_WORKSPACE/generated_content.html

        # Insert the new content into template.html and output to index.html
        awk -v new_content="$new_content" '{gsub(/<!--template-->/, new_content)}1' template.html > index.html.tmp
        mv index.html.tmp index.html

    - name: Show generated content
      run: |
        cat $GITHUB_WORKSPACE/generated_content.html

    - name: Add generated_content.html
      run: |
        git add $GITHUB_WORKSPACE/generated_content.html

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html
        git commit -m 'Update index.html with latest blog entries'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
